### ISSUE TITLE
'Attribute' schema field definitions and names

### ISSUE THREAD

**Issue by mbrush** [NCATSTranslator/ReasonerAPI#192]
TRAPI is moving toward use of an exclusively Attribute-based modeling pattern for all Edge metadata, including EPC information. This means there will be no explicit/named fields in the TRAPI spec for Edge metadata. Instead, Attribute objects will be created, where the meaning of the attribute and the value it holds are all defined 'in the data'. 

The Biolink and TRAPI teams have agreed to enhancing the initial TRAPI Attribute object with additional fields to increase its expressivity, and ability to capture more meaningful EPC metadata on edges. These new fields will let it represent how the value an Attribute holds relates to the Edge it hangs from w.r.t. its significance as evidence or provenance metadata.
- e.g. does a publication represent a source of the assertion made in the edge, or a source of data used as evidence to generate it?
- e.g. does a piece of experimental data represent evidence supporting or disputing the edge?
- e.g. does a orcid represent an agent who authored the knowledge, curated evidence for it, or provided a record of it to a KP?
 
We proposed two additional fields to capture this information:  
- **'attribute_type_id'** holds a `curie` for an ontology term representing the nature of the relationship that holds between the value of the Attribute, and the Edge it hangs from (SEPIO will provide most of these)
- **'attribute_from_source'** takes a `string` that captures the specific language/term used by the original source to describe this relationship. This may be a column name in a source cvs file, or a key in a source json document, for the field holding this information.  Capturing this information, where possible,  lets us preserve what the original source said.
 
We also proposed new names for existing slots that makes it clearer what information they hold, and distinguishes them from the new fields. 

There is general agreement about the utility of slots to capture this type of information. But naming of these slots has proved perhaps the most challenging task. We have iterated on many naming approaches and conventions.  Richard, Deepak, Vlado, and myself recently looked at all feedback on this topic and case up with a couple sets of names that we feel address many of the concerns / perspectives raised in Biolink/TRAPI discussions. 

Below we lay out two naming schemes for the schema itself ('Attribute' vs 'ExtensionSlot'), and names of fields the schema defines. The field names are somewhat verbose in order to be explicit about what belongs in each field (but we felt this is important in this case, given the nuanced distinctions made by the model).  Detailed definitions for each field can be found [here](https://github.com/NCATSTranslator/Evidence-Provenance-Confidence-Working-Group/blob/master/Attribute_object_examples.yaml), if needed. 

The rationale behind these proposals is based on an understanding of an Attribute object as the reification of a named edge/node slot.  Therefore, the reified object needs a field to capture the id/name of the slot being reified, and the value that slot holds. TRAPI adds a few more fields to capture additional metadata. 
 
### Proposal 1: ‘Attribute’ Schema
Preserves the schema name ‘Attribute’, defines a principled/coherent set of field names 
 
````
 Attribute:
  - attribute_type_id: curie [0..1]          # formerly 'relationship_id', 'attribute_id', 'attribute_type', 'relation_id'
  - attribute_from_source: string [0..1]     # formerly 'source_relationship', 'attribute_name', relation_name'
  - value: string [1..m]                     
  - value_type_id: curie [0..1]              # formerly 'value_type', 'type'
  - value_type_from_source: string [0..1]    # formerly 'source_value_type', 'value_type_name'
  - value_source: string [0..1]              # formerly 'source'
  - value_url: string [0..m]                 # formerly 'url'
  - description: string [0..1]              
 ````

### Proposal 2: ‘ExtensionSlot’ Schema
Parallels the proposal above, but adopts terminology based on FHIR (‘[Extension](https://www.hl7.org/fhir/extensibility.html)’) and Biolink ‘slot’). Note that it proposes a new name for the Attribute object (‘ExtensionSlot’), and the proposed field names are defined based on this new name. 

The rationale for this proposal is that Attributes provide a mechanism to 'extend' the model with new slots, without modifying the actual schema with new named fields. This is the precise purpose of the FHIR 'Extension' element - and its two core fields correspond to the core fields in the Attribute object (one capturing the name of the reified slot, and one holding the value of this slot). The name 'ExtensionSlot' focuses on this function that this object provides - rather than what the object captures. Use of the term 'Extension' in the schema name lets us avoid the overloaded term 'Attribute', and use of the term 'Slot' preserves alignment with Biolink vernacular, and reflects the idea that this object represents a reified Biolink slot. 

```` 
ExtensionSlot:
  - slot_type_id: curie [0..1]              # formerly 'relationship_id', 'attribute_id', 'attribute_type', 'relation_id'
  - slot_from_source: string [0..1]         # formerly 'source_relationship', 'attribute_name', relation_name'
  - slot_value: string [1..m]               # formerly 'value'
  - value_type_id: curie [0..1]             # formerly 'value_type', 'type'
  - value_type_from_source: string [0..1]   # formerly 'source_value_type', 'value_type_name'
  - value_source: string [0..1]             # formerly 'source'
  - value_url: string [0..m]                # formerly 'url'
  - description: string [0..1]            
````
