### ISSUE TITLE
Should comma be allowed in predicate?

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/ReasonerAPI#205]
Currently the comma is not permitted in a predicate:
https://github.com/NCATSTranslator/ReasonerAPI/blob/f61506b5185e56d82a34a2ad9bd60d11843eaf4f/TranslatorReasonerAPI.yaml#L585
```
pattern: ^biolink:[a-z][a-z_]*$
```

But ARAX has some commas and therefore appears in violation of this and is not schema compliant.

But ARAX has it because BioLink appears to have it:
https://github.com/biolink/biolink-model/blob/70a73ad20dee03e24b559e5eaef81c3eb0f4ee0b/biolink-model.yaml#L2492
```
  positively regulated by, entity to entity:
    is_a: regulated by, entity to entity
    inverse: positively regulates, entity to entity

  negatively regulates, entity to entity:
    aliases: ['activity directly negatively regulates activity of']
    is_a: regulates, entity to entity
    mixins:
      - negatively regulates
    inverse: negatively regulated by, entity to entity
    local_names:
      translator: negatively regulates
      ro: activity directly negatively regulates activity of
    in_subset:
      - translator_minimal
    exact_mappings:
      - RO:0002449
```

What is the solution?
Add comma to the regexp?
Or continue to disallow comma after resolving this apparent paradox.
