### ISSUE TITLE
Adding context to One-Hop Queries

### ISSUE THREAD

**Issue by yakaboskic** [NCATSTranslator/ReasonerAPI#232]
CHP has been struggling to link biolink predicates with clinical data inference similar to other clinical KPs. For instance, the query: drug treats disease, works fine for a KP that has an edge association of a similar form in their knowledge base, but what does "treats" mean quantitatively? For CHP, we have various entities that could be used to transform "treats" into a quantitative entity that we can use like increasing patient survival time, or decreasing tumor staging, etc. We have previously asked ARA/Users to specify these "proxies" and any additional "contexts" using a multi-hop query structure. However, this request has caused a variety of implementation issues and we are now wanting to compress our query graphs into a one-hop structure with context. 

In consolidating our structure and the new improvements present in TRAPI 1.1, we wanted to present how we are adding predicate proxies and contexts to QEdges. We'd like to see how teams, particularly the TRAPI experts, feel about this and maybe something of this form could lead to a standard eventually. 

Example Query Graph with predicate proxies and context in the QEdge for "Drug treats disesase:"

```
query_graph:
 nodes:
    n0:
      ids:
      - CHEMBL:CHEMBL88
      categories:
      - biolink:Drug
    n1:
      ids:
      - MONDO:0004989
      categories:
      - biolink:Disease
  edges:
    e0:
      subject: n0
      object: n1
      predicate: biolink:treats
      constraints:
      - name: predicate_proxy
        operator: matches
        not: false
        value: survival_time
      - name: survival_time
        id: EFO:0000714
        operator: >=
        not: false
        value: N
      - name: predicate_context
        operator: ==
        not: false
        value: [biolink:Gene]
      - name: Gene Mutations
        id: biolink:Gene
        operator: in
        not: false
        value: [ENSEMBL:ENS0000001666263]
```
