### ISSUE TITLE
Add properties to the RetrievalSource object 

### ISSUE THREAD

**Issue by mbrush** [NCATSTranslator/ReasonerAPI#392]
Per outcome of voting in #386, we settled on Proposal 2 (aka Candidate B in #369). 

But the proposed RetrievalSource object lacks some of the additional metadata fields found in the TRAPI Attribute object, which are used in practice used to pass along certain types of info about a primary or aggregator source (e.g. description, url, etc).   We should enhance the bare bones RetrievalSource object as proposed in #369 with a couple additional fields to hold relevant additional info about a source InfoResource.

The proposal below adds a `description` field and a `resource_url` field (to replicate `Attribute.description`, and `Attribute.value_url`, respectively).  In addition, it suggests an additional `source_record_url` field that can be used to hold the url of a specific record of the knowledge that was retrieved an reported in the Edge - which would address the request in [EPC #6](https://github.com/NCATSTranslator/Evidence-Provenance-Confidence-Working-Group/issues/6).

````
RetrievalSource:
  - resource: urlorcurie
  - resource_role:  enum 
  - upstream_resource: urlorcurie
 # New proposed fields
  - resource_description: string
  - resource_url: urlorcurie
  - source{_record_url: urlorcurie
````
